version: "3.9"

services:
  postgres:
    container_name: spotify
    image: postgres:11.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotify
    ports:
      - "5432:5432"